# Site settings
title: My Favorite Blog
email: me@example.com
description: > # this means to ignore newlines until "baseurl:"
 This is my favorite website ever.
 This is a second line of text.
 And a third line here!

baseurl: "/path/to/baseurl/" # the subpath of your site, e.g. /blog/
url: "https://base.hostname.com/" # the base hostname & protocol for your site

twitter_username: meontwitter
github_username:  meonGitHub

# Build settings
markdown: kramdown
